"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import { ArrowRight, Heart, Leaf, Minus, Plus, ShoppingBag, Truck, X } from "lucide-react";
import Link from "next/link";
import { Brand } from "@/components/Brand";
import { fallbackProducts, money, type Product } from "@/lib/products";
import { supabaseBrowser } from "@/lib/supabase/browser";

type CartLine={id:string;quantity:number};
function startGoogleLogin(){try{const client=supabaseBrowser();void client.auth.signInWithOAuth({provider:"google",options:{redirectTo:`${location.origin}/auth/callback`}}).then(({error})=>{if(error)alert("Google sign-in couldn’t start. Check the Supabase Google provider setup.");});}catch{alert("Add your Supabase project URL and anon key to .env.local to enable Google sign-in.");}}

export default function Home(){
  const [products,setProducts]=useState<Product[]>(fallbackProducts),[cart,setCart]=useState<CartLine[]>([]),[cartId,setCartId]=useState(""),[drawer,setDrawer]=useState(false),[category,setCategory]=useState("All pieces"),[search,setSearch]=useState(""),[user,setUser]=useState<string|null>(null);
  const cartLoaded=useRef(false);
  useEffect(()=>{let alive=true;try{let id=localStorage.getItem("shopfite-cart-id");if(!id){id=crypto.randomUUID();localStorage.setItem("shopfite-cart-id",id);}setCartId(id);const local=localStorage.getItem("shopfite-cart");if(local)setCart(JSON.parse(local));fetch(`/api/cart?cartId=${encodeURIComponent(id)}`).then(r=>r.ok?r.json():Promise.reject()).then(d=>{if(alive&&Array.isArray(d.items)){setCart(d.items);if(d.cartId){setCartId(d.cartId);localStorage.setItem("shopfite-cart-id",d.cartId);}}}).catch(()=>{}).finally(()=>{if(alive)cartLoaded.current=true;});}catch{cartLoaded.current=true;}fetch("/api/products").then(r=>r.json()).then(d=>Array.isArray(d)&&d.length&&setProducts(d)).catch(()=>{});try{const client=supabaseBrowser();client.auth.getUser().then(({data})=>setUser(data.user?.email??null));const {data:{subscription}}=client.auth.onAuthStateChange((_e,session)=>setUser(session?.user.email??null));return()=>{alive=false;subscription.unsubscribe();};}catch{return()=>{alive=false;};}},[]);
  useEffect(()=>{if(!cartLoaded.current)return;localStorage.setItem("shopfite-cart",JSON.stringify(cart));if(cartId){const timer=setTimeout(()=>{void fetch("/api/cart",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({cartId,items:cart})});},350);return()=>clearTimeout(timer);}},[cart,cartId]);
  useEffect(()=>{if(!user||!cartId)return;let alive=true;const sync=()=>{void fetch(`/api/cart?cartId=${encodeURIComponent(cartId)}`).then(r=>r.ok?r.json():Promise.reject()).then(d=>{if(!alive)return;if(d.cartId&&d.cartId!==cartId){setCartId(d.cartId);localStorage.setItem("shopfite-cart-id",d.cartId);}if(Array.isArray(d.items))setCart(current=>JSON.stringify(current)===JSON.stringify(d.items)?current:d.items);}).catch(()=>{});};const timer=window.setInterval(sync,1200);const focus=()=>sync();window.addEventListener("focus",focus);return()=>{alive=false;window.clearInterval(timer);window.removeEventListener("focus",focus);};},[user,cartId]);
  const categories=["All pieces",...new Set(products.map(p=>p.category))];
  const shown=useMemo(()=>products.filter(p=>(category==="All pieces"||p.category===category)&&`${p.name} ${p.category}`.toLowerCase().includes(search.toLowerCase())),[products,category,search]);
  const lines=cart.map(line=>({ ...line, product:products.find(p=>p.id===line.id) })).filter(line=>line.product);
  const count=cart.reduce((n,line)=>n+line.quantity,0);
  const add=(id:string)=>setCart(current=>{const found=current.find(line=>line.id===id);return found?current.map(line=>line.id===id?{...line,quantity:line.quantity+1}:line):[...current,{id,quantity:1}];});
  const quantity=(id:string,delta:number)=>setCart(current=>current.map(line=>line.id===id?{...line,quantity:line.quantity+delta}:line).filter(line=>line.quantity>0));
  const signOut=async()=>{try{await supabaseBrowser().auth.signOut();}catch{}setUser(null);};
  return <>
    <header className="site-header"><Brand/><nav className="nav-links"><a href="#shop">Shop</a><a href="#story">Our story</a><a href="#footer">Journal</a></nav><div className="header-actions"><span className="subtle" style={{fontSize:12}}> {user?user:""}</span>{user?<button className="icon-button" onClick={signOut}>Sign out</button>:<button className="icon-button" onClick={startGoogleLogin}>Sign in</button>}<button className="icon-button" aria-label="Open shopping bag" onClick={()=>setDrawer(true)}><ShoppingBag size={19}/><span>Bag ({count})</span></button></div></header>
    <main><section className="hero"><div><div className="eyebrow">Good things, thoughtfully made</div><h1>Make room for<br/>the everyday.</h1><p>Useful, well-made things for a slower, more considered kind of living. Designed with care, chosen to last.</p><a className="button" href="#shop">Explore the collection <ArrowRight size={16}/></a></div><div className="hero-art"><img src="https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=1000&q=90" alt="Calm, sunlit living room with natural textures"/></div></section>
    <div className="trust-row"><span><Leaf size={16}/> Materials with care</span><span><Truck size={16}/> Free delivery over ₦1,500</span><span><Heart size={16}/> Made for real life</span></div>
    <section className="section" id="shop"><div className="section-head"><div><div className="eyebrow">The considered edit</div><h2>Everyday, elevated.</h2></div><label style={{position:"relative"}}><span style={{position:"absolute",left:12,top:12,color:"#778"}}>⌕</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Find something…" aria-label="Search products" style={{height:40,padding:"0 12px 0 34px",border:"1px solid var(--line)",background:"transparent",width:190}}/></label></div>
    <div className="category-row">{categories.map(c=><button key={c} className={`chip ${category===c?"active":""}`} onClick={()=>setCategory(c)}>{c}</button>)}</div>
    <div className="grid">{shown.map((p,index)=><article className="product-card" key={p.id}><div className="product-image"><img src={p.image_url} alt={p.name} loading="lazy"/>{p.badge&&<span className="badge">{p.badge}</span>}<button className="add" onClick={()=>{add(p.id);setDrawer(true);}} aria-label={`Add ${p.name} to bag`}><Plus size={18}/></button></div><div className="product-meta"><div><h3>{p.name}</h3><p>{p.category}</p></div><span className="price">{money(p.price_cents)}</span></div></article>)}</div>{shown.length===0&&<p className="empty">No pieces found. Try a different search.</p>}</section>
    <section className="promo" id="story"><div><div className="eyebrow" style={{color:"#c8e18b"}}>A little more considered</div><h2>Buy less. Love it longer.</h2><p>Thoughtful materials, enduring design, and details worth coming home to.</p></div><a className="button" href="#shop">Shop the collection <ArrowRight size={16}/></a></section></main>
    <footer className="footer" id="footer"><Brand/><span>Good things for everyday living.</span><span>© 2026 ShopFite</span></footer>
    {drawer&&<div className="modal-backdrop" onClick={()=>setDrawer(false)}><aside className="drawer" onClick={e=>e.stopPropagation()}><div className="drawer-head"><h2>Your bag <span style={{color:"var(--muted)",fontWeight:400}}>({count})</span></h2><button className="close" aria-label="Close bag" onClick={()=>setDrawer(false)}><X/></button></div>{lines.length===0?<div className="empty"><ShoppingBag size={32}/><p>Your bag is waiting for something lovely.</p><button className="button" onClick={()=>setDrawer(false)}>Continue shopping</button></div>:<>{lines.map(({product:p,quantity:q,id})=><div className="cart-item" key={id}><img src={p!.image_url} alt=""/><div className="cart-item-main"><h3>{p!.name}</h3><p>{money(p!.price_cents)}</p><div className="qty"><button aria-label="Decrease quantity" onClick={()=>quantity(id,-1)}><Minus size={12}/></button><span>{q}</span><button aria-label="Increase quantity" onClick={()=>quantity(id,1)}><Plus size={12}/></button></div></div><strong>{money(p!.price_cents*q)}</strong></div>)}<div className="cart-total"><span>Subtotal</span><span>{money(lines.reduce((s,l)=>s+l.product!.price_cents*l.quantity,0))}</span></div><p className="subtle">Delivery is calculated at checkout. Free on orders over ₦1,500.</p><Link className="button full" href="/checkout" onClick={()=>setDrawer(false)}>Continue to checkout <ArrowRight size={16}/></Link></>}</aside></div>}
  </>;
}
