"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { Brand } from "@/components/Brand";
import { ArrowLeft, ArrowRight, Check, LockKeyhole, ShoppingBag } from "lucide-react";
import { fallbackProducts, money, type Product } from "@/lib/products";
import { supabaseBrowser } from "@/lib/supabase/browser";
type CartLine={id:string;quantity:number};
const blank={name:"",email:"",phone:"",address:"",city:"",region:"",notes:""};
export default function Checkout(){
 const [cart,setCart]=useState<CartLine[]>([]),[cartId,setCartId]=useState(""),[cartReady,setCartReady]=useState(false),[products,setProducts]=useState<Product[]>(fallbackProducts),[form,setForm]=useState(blank),[busy,setBusy]=useState(false),[error,setError]=useState(""),[placed,setPlaced]=useState(""),[emailSent,setEmailSent]=useState(false);
 useEffect(()=>{let alive=true;try{let id=localStorage.getItem("shopfite-cart-id");if(!id){id=crypto.randomUUID();localStorage.setItem("shopfite-cart-id",id);}setCartId(id);const local=localStorage.getItem("shopfite-cart");if(local)setCart(JSON.parse(local));fetch(`/api/cart?cartId=${encodeURIComponent(id)}`).then(r=>r.ok?r.json():Promise.reject()).then(d=>{if(alive&&Array.isArray(d.items))setCart(d.items);}).catch(()=>{}).finally(()=>{if(alive)setCartReady(true);});}catch{setCartReady(true);}fetch("/api/products").then(r=>r.json()).then(d=>Array.isArray(d)&&d.length&&setProducts(d)).catch(()=>{});try{const client=supabaseBrowser();client.auth.getUser().then(({data})=>{if(data.user){setForm(f=>({...f,email:f.email||data.user!.email||"",name:f.name||data.user!.user_metadata?.full_name||""}));}});}catch{}return()=>{alive=false;};},[]);
 const lines=cart.map(line=>({...line,product:products.find(p=>p.id===line.id)})).filter(l=>l.product),subtotal=useMemo(()=>lines.reduce((n,l)=>n+l.product!.price_cents*l.quantity,0),[lines]),shipping=subtotal>=150000?0:12000;
 const google=()=>{try{void supabaseBrowser().auth.signInWithOAuth({provider:"google",options:{redirectTo:`${location.origin}/auth/callback?next=/checkout`}}).then(({error})=>{if(error)setError("Google sign-in is unavailable. Check your Supabase provider settings.");});}catch{setError("Add Supabase credentials to enable Google sign-in.");}};
 async function submit(e:FormEvent){e.preventDefault();setError("");if(!cartReady){setError("Your bag is still loading. Please try again in a moment.");return;}if(!lines.length){setError("Your bag is empty. Add an item before checking out.");return;}setBusy(true);try{const response=await fetch("/api/checkout",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({customer:form,items:cart})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Checkout failed.");localStorage.setItem("shopfite-cart","[]");if(cartId)void fetch("/api/cart",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({cartId,items:[]})});setCart([]);setEmailSent(Boolean(data.emailSent));setPlaced(data.orderNumber);}catch(e){setError(e instanceof Error?e.message:"Checkout failed. Please try again.");}finally{setBusy(false);}}
 if(placed)return <><header className="site-header"><Brand/><span className="subtle">Secure checkout</span></header><main className="success"><div className="check"><Check size={30}/></div><div className="eyebrow">Order received</div><h1 style={{font:"600 36px Manrope",letterSpacing:"-1px"}}>Thank you for your order.</h1><p className="subtle">Your order number is <strong>{placed}</strong>. {emailSent?"A confirmation email is on its way.":"We couldn’t send a confirmation email, but your order is saved. Our team will be in touch to confirm delivery and payment on arrival."}</p><Link className="button" href="/">Back to the shop <ArrowRight size={16}/></Link></main></>;
 return <><header className="site-header"><Brand/><span className="subtle"><LockKeyhole size={14} style={{verticalAlign:"middle"}}/> Secure checkout</span><Link className="icon-button" href="/" style={{fontSize:13}}>Continue shopping</Link></header><main className="checkout-wrap"><div><Link className="text-link" href="/" style={{display:"inline-flex",alignItems:"center",gap:5,marginBottom:23}}><ArrowLeft size={15}/> Back to shop</Link><h1>Checkout</h1><p className="subtle">You’re just a few details away from the good stuff.</p><div className="form-section"><h2>Express checkout</h2><button type="button" className="google" onClick={google}><b style={{color:"#4285f4",fontSize:18}}>G</b> Continue with Google</button><div className="auth-line">or continue as a guest</div></div>
 <form onSubmit={submit}><div className="form-section" style={{marginTop:0}}><h2>Contact information</h2><div className="form-grid"><div className="field wide"><label htmlFor="email">Email address</label><input required type="email" id="email" autoComplete="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="you@example.com"/></div><div className="field"><label htmlFor="name">Full name</label><input required id="name" autoComplete="name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Your name"/></div><div className="field"><label htmlFor="phone">Phone number</label><input required type="tel" id="phone" autoComplete="tel" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="+234 800 000 0000"/></div></div></div>
 <div className="form-section"><h2>Delivery address</h2><div className="form-grid"><div className="field wide"><label htmlFor="address">Street address</label><input required id="address" autoComplete="street-address" value={form.address} onChange={e=>setForm({...form,address:e.target.value})} placeholder="House number and street"/></div><div className="field"><label htmlFor="city">City</label><input required id="city" autoComplete="address-level2" value={form.city} onChange={e=>setForm({...form,city:e.target.value})}/></div><div className="field"><label htmlFor="region">State / region</label><input required id="region" autoComplete="address-level1" value={form.region} onChange={e=>setForm({...form,region:e.target.value})}/></div><div className="field wide"><label htmlFor="notes">Delivery notes <span style={{fontWeight:400,color:"var(--muted)"}}>(optional)</span></label><input id="notes" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="Gate code, directions, or other notes"/></div></div></div>
 <div className="form-section"><h2>Payment</h2><div className="notice"><strong>Cash on delivery</strong><br/>Pay the total when your order arrives. We’ll contact you to confirm your delivery.</div></div>{error&&<p className="error" role="alert">{error}</p>}<button className="button full" disabled={busy}>{busy?"Placing your order…":<>Place order · {money(subtotal+shipping)} <ArrowRight size={16}/></>}</button><p className="subtle" style={{fontSize:11,textAlign:"center",lineHeight:1.6}}>By placing your order, you agree to our terms and privacy policy.</p></form></div>
 <aside className="summary"><h2>Your order <span style={{fontWeight:400,color:"var(--muted)"}}>({lines.reduce((n,l)=>n+l.quantity,0)})</span></h2>{lines.map(({product:p,quantity:q,id})=><div className="summary-row" key={id} style={{alignItems:"center",gap:12}}><div style={{display:"flex",alignItems:"center",gap:11}}><img src={p!.image_url} alt="" style={{width:52,height:58,objectFit:"cover"}}/><span>{p!.name} × {q}</span></div><strong>{money(p!.price_cents*q)}</strong></div>)}{!lines.length&&<p className="subtle">Your bag is empty.</p>}<div className="summary-row"><span>Subtotal</span><span>{money(subtotal)}</span></div><div className="summary-row"><span>Delivery</span><span>{shipping?money(shipping):"Free"}</span></div><div className="summary-row summary-total"><span>Total due on delivery</span><span>{money(subtotal+shipping)}</span></div><p className="subtle" style={{fontSize:12,marginTop:20,lineHeight:1.6}}><ShoppingBag size={14} style={{verticalAlign:"middle"}}/> Free delivery on orders over ₦1,500.</p></aside></main></>;
}
